### ISSUE TITLE
A deprecated SciPy import causes the KASOC filter to fail testing

### ISSUE THREAD

**Issue by lmcarboneau** [tasoc/corrections#13]
Import is **scipy.misc.factorial**

According to the [documentation](https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.misc.factorial.html) this import of SciPy's `factorial` routine is deprecated as of 1.0.0.

The KASOC filter should be checked - if the routine is significantly different, we should add `scipy < 1.0.0` to the `requirements.txt`
if not, the KASOC filter should be updated so that it [imports `scipy.special.factorial` instead](https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.special.factorial.html#scipy.special.factorial)

![image](https://user-images.githubusercontent.com/4117599/58986893-58799b00-87ac-11e9-8557-5097b7a0e367.png)
![image](https://user-images.githubusercontent.com/4117599/58986935-70511f00-87ac-11e9-9013-5865faab120d.png)

This should have come up in testing earlier, so I'm not sure why it's suddenly failing tests now. Feel free to close the issue if the build is passing

**Comment by rhandberg** [comment]
Is this still a problem?

**Comment by rhandberg** [comment]
Should be fixed by https://github.com/tasoc/corrections/commit/8a5a91405e044f5541fac08334b6be4624d0f087.
