### ISSUE TITLE
Ensemble Metric-based Optimization

### ISSUE THREAD

**Issue by lmcarboneau** [tasoc/corrections#16]
Restructuring ensemble code to support using an adaptable ensemble size based on the metric.

**Implementation:**
- [ ] Functionalize ensemble member additions out of the main loop
    - [x] Move existing code out of `do_correction`
    - [x] Verify parameters
    - [ ] Verify implementation of algorithm 
    - [ ] Verify passed objects maintain the expected structure
    - [x] Test calling
- [ ] Functionalize correction application
    - [x] Move existing code out of `do_correction`
    - [x] Verify parameters
    - [ ] Create or add to existing data structure 
    - [ ] Return metric condition?
- [ ] Restructure main loop
    - [x] Change to using function calls
    - [ ] Add metric as break condition: ∑(abs(1st diff))
    - [ ] Return ensemble metadata 
- [ ] Test that the results are consistent

**Questions**
- [ ] Can we speed up using different built in numpy/astropy functions
- [ ] Can we reduce overhead using different data structures

**Comment by ojhall94** [comment]
> Addition ensemble members, sigma clilpping happening. Need to look and decide whether its just sigma clipping causing overhead increase or whether we can speed that up

From chat with lindsey, I'll try and do that tomorrow
