### ISSUE TITLE
Ensemble removes nans from input lightkurve, which it shouldn't

### ISSUE THREAD

**Issue by ojhall94** [tasoc/corrections#8]
The corrector code requires that the length of the input flux and the output flux is the same--- at the moment the ensemble code removes all nans from the dataset, making the length of the output flux smaller. We should either mask the nans or reinsert.

**Comment by ojhall94** [comment]
This is now tested for in the new unit tests in #6. I will try and resolve and then merge this into devel.

**Comment by ojhall94** [comment]
Update: Its the quality mask excluding these data, not the nans!

**Comment by ojhall94** [comment]
I have commented out this feature as the code still runs. We will need to change the ensemble code so that we keep a record of which points were removed and reinsert them at the end. Tagging @Fill4 for visibility :)

**Comment by lmcarboneau** [comment]
This has been fixed with the updated ensemble algorithm!  The code can probably be optimized, but it's working properly with the changes:

```python
# Replace removed points with NaN's so the info can be saved to the FITS
        lc_corr.time = lc_corr.time[lc_quality_mask]
        lc_corr.flux = lc_corr.flux[lc_quality_mask]
        lc_corr.flux_err = lc_corr.flux_err[lc_quality_mask]
        if len(lc_corr.flux) != len(og_time):
            fix_flux = np.asarray(lc_corr.flux.copy())
            indices = np.array(np.where(np.isin(og_time, lc_corr.time, assume_unique=True, invert=True)))[0]
            indices.tolist()

            for ind in indices:
                fix_flux = np.insert(fix_flux, ind, np.nan)

            lc_corr.flux = fix_flux.tolist()
            lc_corr.time = og_time
```

see [`ensemble.py`](https://github.com/tasoc/corrections/blob/ensemble_comments/corrections/ensemble.py) for specifics
 (line 346, just before the return)

**Comment by rhandberg** [comment]
Marking this issue as closed
